### PR TITLE
Update to Gnome Forty

### LINKED ISSUE #195: Extension settings broken under GNOME 40
The extension's panel components work fine if the metadata.json is updated to include shell versions "40.beta" and "40", but the preferences dialogue does not. Instead I get a 'Something's gone wrong' box with the following error:

```
TypeError: w.show_all is not a function

Stack trace:
  buildPrefsWidget@/usr/share/gnome-shell/extensions/freon@UshakovVasilii_Github.yahoo.com/prefs.js:134:7
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

### PR DESCRIPTION
**Pull request by brianegan**
Fixes #195

### CODE REVIEW

**Comment by audreytoskin** [comment]
This does seem to fix GNOME 40 compatibility. I tested in a virtual machine, so I couldn't confirm that the new revision is still able to display sensor information -- because the VM doesn't have any sensors -- but brianegan at least fixes the issue where the extension couldn't be enabled at all. And I assume the lm_sensors APIs haven't changed.

**Comment by brianegan** [comment]
"Works on my machine?" :laughing: 

sensors
settings

**Comment by frosth555** [comment]
i've run this extension with gnome40 since few days without issues, well done sir. :)

**Comment by fabrixx** [comment]
Work well an my 

Arch with fixes!!
Thanks

Senzansssssssssome
Senzanoaaaaaame

**Comment by RuiGuilherme** [comment]
Patch works fine here. Journalctl not log any issue.

Captura de tela de 2021-04-08 04-10-21

**Pull request merged**
