### PR TITLE
[WIP] Add debug logging, fixes #103

### LINKED ISSUE #103: Option to enable/disable logs
Currently extension write some logs at start. We can add option to enable disable logs.

### PR DESCRIPTION
**Pull request by tingvarsson**
To enable more debug logging without custom builds while still
maintaining a minimal syslog impact by default

- Add a settings variable 'debug', hidden from the user
- Use dconf to write/read it (suggest adding to the README and/or
  wiki). Only for debugging purposes really
- When 'debug' is set it will enable the possibility of extra logging
- The new 'debug' function also adds in some meta data such as unique
  syslog id instead of gnome-shell, file/func/line id to easier locate
  in code
- Changed the Render all MenuItems and a couple of outcommented
  updated logs to use the new debug function instead

Todo's before no longer WIP:
- Place it somewhere else than in this, cause I presume it wont be
reachable everywhere then
- Consider replacing regular log with something like this as well (to
gain the neat meta data (extension prefix, file, func, line))
- Think some more on the usage of log domains and if possible to turn
of more logging that way instead of dconf variable

### CODE REVIEW

**Comment by tingvarsson** [comment]
[WIP] as in Work In Progress, I wanted to share what I'd done so far. Wasn't fully sure it was merge ready yet. But I assume you liked it? :)

**Comment by UshakovVasilii** [comment]
I thought it was first part of pull request related to logs ))
I like it, we don't spam journal and logs can enabled at runtime `dconf write /org/gnome/shell/extensions/freon/debug 'boolean true'`. Great!

**Comment by UshakovVasilii** [comment]
I didn't release this version on extensions.gnome.org yet, so it development version for now

**Comment by tingvarsson** [comment]
Okay I see! Glad you liked it so far. :)
Will look at my remaining items some time during the week when I have time.

**Pull request merged**
