### PR TITLE
Fix maximum temperature goes down

### PR DESCRIPTION
**Pull request by biji**

### CODE REVIEW

**Comment by UshakovVasilii** [comment]
Hi, "Maximum" should show current maximum temperature. It shouldn't show maximum temperature for all time.

**Comment by biji** [comment]
Hi.. 
IMHO maximum temperature should apply in one session/login. For example I want to know what max temp while playing game (I want to compare when using coolpad or not)

Thanks

**Comment by UshakovVasilii** [comment]
I'll think about max session temperature for each sensor functionality #21. But "Maximum" should show current maximum temperature.

**Comment by fedotxxl** [comment]
@UshakovVasilii Can you suggest a case when the current maximum implementation useful? 
I also thought that it's maximum per session - to monitor maximum CPU temperature

**Comment by AlexWayfer** [comment]
> @UshakovVasilii Can you suggest a case when the current maximum implementation useful?
> I also thought that it's maximum per session - to monitor maximum CPU temperature

I use it. It's like… computer's actual temperature for me. Like if your body has different temperatures in different places, you're taking a maximum one (it's 36.6 for healthy people, other places on skin and body has lower temperature). So, I just monitoring the most problematic place in my computer, for any task (CPU-related, GPU or SSD), especially when I do something heavy, and only if this maximum goes high (like above 70°) — I can open the extension menu and check what actually gives it.

**Comment by araruna** [comment]
> > @UshakovVasilii Can you suggest a case when the current maximum implementation useful?
> > I also thought that it's maximum per session - to monitor maximum CPU temperature
> 
> I use it. It's like… computer's actual temperature for me. Like if your body has different temperatures in different places, you're taking a maximum one (it's 36.6 for healthy people, other places on skin and body has lower temperature). So, I just monitoring the most problematic place in my computer, for any task (CPU-related, GPU or SSD), especially when I do something heavy, and only if this maximum goes high (like above 70°) — I can open the extension menu and check what actually gives it.

Although it is interesting to have this perspective, I believe the name is misleading. I also thought that it referred to the maximum so far (in the current session).

Regardless, I would like to be able to see the latter, as I'm currently trying to monitor if my CPU is prone to overheating.

**Comment by mirao** [comment]
Could you explain me how Maximum works?
E.g. when I run a CPU benchmark, the current and maximum temperature will increase from 41° => 62° and it makes sense :heavy_check_mark: .
When the CPU benchmark finishes, the current temperature decreases back to 41° :heavy_check_mark: , but maximum decreases to 48° :confused:
How is the maximum value computed?

**Pull request closed without merging**
